const RIDE_NEEDS = {
  WHEELCHAIR_ACCESSIBLE: 'WHEELCHAIR_ACCESSIBLE',
  EXTRA_LUGGAGE_SPACE: 'EXTRA_LUGGAGE_SPACE',
  PET_FRIENDLY: 'PET_FRIENDLY',
  CHILD_SEAT: 'CHILD_SEAT',
} as const;


const RIDE_STATUS = {
  ACCEPTED: 'ACCEPTED',
  ON_GOING: 'ON_GOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;



const PAYMENT_METHOD = {
  CASH: 'CASH',
  WALLET: 'WALLET',
  CARD: 'CARD',
} as const;

const CANCELLED_BY = {
  RIDER: 'RIDER',
  DRIVER: 'DRIVER',
  SYSTEM: 'SYSTEM',
} as const;

const REFUND_STATUS = {
  PENDING: 'PENDING',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
} as const;


export const RideConstants = {
    RIDE_NEEDS,
    RIDE_STATUS,
    PAYMENT_METHOD,
    CANCELLED_BY,
    REFUND_STATUS,
}